language: node_js
node_js:
  - '12.8.1'

cache:
  - npm

script:
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local_dir: build
  on:
    branch: master
