export enum UsersType {
  SET_USERS = 'USERS/SET_USERS',
  GET_USERS = 'USERS/GET_USERS',
  SET_LOADING = 'USERS/SET_LOADING',
  TOGGLE_CHECK = 'USERS/TOGGLE_CHECK',
  LOAD_MORE = 'USERS/LOAD_MORE',
  SET_ERROR = 'USERS/SET_ERROR',
  RESET_ERROR = 'USERS/RESET_ERROR'
}
